import Head from "next/head";
import styles from "../styles/Home.module.css";
import submitdata from "../teamsubmissions.json";
import { useState } from "react";

const Submission = ({ sub }: any) => {
  const [open, setOpen] = useState(false);
  return (
    <div className="border p-2 my-2 rounded">
      {open ? (
        <div>
          <button onClick={() => setOpen(false)} className={``}>
            {/* <div>{key}</div> */}
            <div>close</div>
          </button>
          {Object.keys(sub).map((key) => {
            return (
              <>
                <div key={key} className="">
                  {/* <div>{key}</div> */}
                  <div className="font-bold text-l mt-2">{key}</div>
                  {key === "Upload A Sponsor Me Video" ? (
                    <a href={sub[key]} target="_blank" rel="noreferrer">
                      View Video
                    </a>
                  ) : (
                    <div>{sub[key]}</div>
                  )}
                </div>
              </>
            );
          })}
        </div>
      ) : (
        <button onClick={() => setOpen(true)} className={`w-full`}>
          {sub.Name}
        </button>
      )}
    </div>
  );
};

export default function Home() {
  // console.log(submitdata);
  return (
    <div className={styles.container}>
      <Head>
        <title>Form Submissions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl">Form Submissions</h1>
        <div>
          {submitdata.map((sub: any, ind: number) => (
            <Submission key={ind} sub={sub} />
          ))}
        </div>
      </main>
    </div>
  );
}
